name: Sync specs submodule

permissions:
  contents: write
  pull-requests: write

on:
  repository_dispatch:
    types: [s2-specs-update]

jobs:
  sync-submodule:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true

      - name: Update submodule
        id: submodules
        uses: sgoudham/update-git-submodules@v2.1.1
        with:
          submodules: specs

      - name: Create pull request
        if: ${{ steps.submodules.outputs['specs--updated'] }}
        uses: peter-evans/create-pull-request@v7
        with:
          committer: s2-helper[bot] <194906454+s2-helper[bot]@users.noreply.github.com>
          author: s2-helper[bot] <194906454+s2-helper[bot]@users.noreply.github.com>
          title: "chore: sync specs submodule"
          branch: "specs/sync-${{ steps.submodules.outputs['specs--latestShortCommitSha'] }}"
          body: ${{ steps.submodules.outputs.prBody }}
